<a href="https://colab.research.google.com/github/rlpinhal/Aprendendo_Python/blob/main/aula_9_biblioteca_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# para instalar uma biblioteca, eu uso o comando:
# no colab: !pip install "nome da biblioteca"
# fora do colab é apenas pip install

!pip install pandas
!pip install numpy
!pip install matplotlib plotly scikit-learn

#na linha 7 tem várias bibliotecas, apenas separadas pelo espaço

In [ ]:
# para colocar a biblioteca em uso, devemos importar ela
# import NOME_DA_BIBLIOTECA as APELIDO_PARA_USO
import pandas as pd

In [ ]:
# criar o 'esqueleto' do arquivo

# para isso, vamos usar dicionários para criar os dados
# dicionário funciona com a ideia de chave-valor ou chave-valores

dados = {
    'nome': ['André', 'Paulo', 'Aline', 'Paola'],
    'idade': [36, 25, 30, 18],
    'cidade': ['Sorocaba', 'Indaiatuba', 'São Paulo', 'Registro']
}

#se colocar aqui o comando print(dados), ele vai dar uma tabela simples
#se colocar o comando display(dados), ele vai dar uma tabela melhorzinha, separada por linhas
#mas o comando display ainda dá uma tabela não mt bonita
#a biblio pandas pode transformar um dicionário em uma 'tabela'
#esse pedaço de tabela é chamado de dataframe (df)

# para transformar o dicionário em uma tabela:
df_dados = pd.DataFrame(dados)
#para gerar a tabela mais bonita:
display(df_dados)

    nome  idade      cidade
0  André     36    Sorocaba
1  Paulo     25  Indaiatuba
2  Aline     30   São Paulo
3  Paola     18    Registro

In [ ]:
# criar um arquivo csv (excel):
#para criar, precisamos de dados
#então chamamos os dados e atribuímos a função "to_extensaodoarquivo":


df_dados.to_csv("teste_dados.csv", index=False)
#no menu do canto esquerdo, aperta na pastinha e abre o arquivo criado
#o arquivo será em extensão csv, que poderá ser baixado

In [ ]:
# como ler um arquivo que me enviaram

df_ler_dados = pd.read_csv('/content/teste_dados.csv')

#comando para ler as primeiras infos do arquivo
df_ler_dados.head()

In [ ]:
# vamos popular a tabela

novos_dados = {
    'nome': ['Flávia', 'Cláudio', 'Fernanda'],
    'idade': [50,63,32],
    'cidade': ['Sorocaba', 'Iguape', 'Curitiba']
}

#sempre q quero trabalhar com dados, preciso fazer ser dados
df_novos_dados = pd.DataFrame(novos_dados)

### agora temos que juntar o antigo com o novo
# juntar = concatenar
# cria a base que vai receber todos os dados
# usa a função pd.concat para juntar os dados
# pd.concat([dados_antigos, dados_novos], ignore_index=True)
df_dados_juntos = pd.concat([df_ler_dados,df_novos_dados],ignore_index=True)

#voltar para o csv
df_dados_juntos.to_csv('teste_dados.csv', index=False)
display(df_dados_juntos)

       nome  idade      cidade
0     André     36    Sorocaba
1     Paulo     25  Indaiatuba
2     Aline     30   São Paulo
3     Paola     18    Registro
4    Flávia     50    Sorocaba
5   Cláudio     63      Iguape
6  Fernanda     32    Curitiba