<a href="https://colab.research.google.com/github/rlpinhal/Aprendendo_Python/blob/main/aula_20_analise_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#bibliotecas de uso padrão
import pandas as pd
#biblioteca de analise
import numpy as np
#biblioteca de funções matemáticas
import matplotlib.pyplot as plt
#biblioteca para gerar gráficos

In [ ]:
# os dados eles estão sujos
# carregar esses dados
df_dados_oscar = pd.read_csv('/content/exercicio_qualidade_dados_oscar.csv', on_bad_lines='warn')

#tentar ver dados
display(df_dados_oscar.head(20))

/tmp/ipykernel_13946/2812369771.py:3: ParserWarning: Skipping line 20: expected 5 fields, saw 6

  df_dados_oscar = pd.read_csv('/content/exercicio_qualidade_dados_oscar.csv', on_bad_lines='warn')

,Ano,Categoria,Indicado,Vencedor,Nota
0,2024,Best Picture,Oppenheimer,Yes,Filme biográfico
1,2024,Best Pictue,Oppenheimmer,Y,Erro de digitação no nome e categoria
2,24,Best Picture,Barbie,No,Ano incompleto
3,2023,best picture,Everything Everywhere All at Once,True,Case inconsistente
4,2023,BEST PICTURE,Everything Everywhere All at Once,1,Duplicado com formato diferente
5,2020,Best Picture,Parasite,1,Espaços extras
6,2020,Best Picture,Parasite,1,Linha duplicada
7,1895,Melhor Filme,L'Arrivée d'un train en gare de La Ciotat,Winner!,Data impossível (Óscares não existiam)
8,NaN,Best Actor,Cillian Murphy,Yes,Ano ausente
9,2022,Best Picture,CODA,Sim,Idioma do boleano alterado
10,1994/03/21,Best Picture,Schindler's List,Yes,Formato de data completo (AAAA/MM/DD)
11,2021,Actor in a Supporting Role,Daniel Kaluuya,True,NaN
12,2021,ACTOR IN A SUPPORTING ROLE,Daniel Kaluuya,TRUE,Outra variação de case
13,dois mil e dez,Best Picture,The King's Speech,Yes,Ano por extenso
14,2019,Best Picture,Green Book,N,NaN
15,2019,Best Picture,Green Book,0,Representação diferente para 'Não'
16,2024,Best Director,Christopher Nolan,NaN,Vencedor em falta
17,2024,Best Director,Christopher Nolan,Yes,Espaço no início do nome
18,2050,Best Picture,Future Movie,Yes,Data no futuro

In [ ]:
# ver onde tem dado nulo e seus tipos
df_dados_oscar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Ano        18 non-null     object
 1   Categoria  19 non-null     object
 2   Indicado   19 non-null     object
 3   Vencedor   18 non-null     object
 4   Nota       17 non-null     object
dtypes: object(5)
memory usage: 892.0+ bytes

In [ ]:
# criar contagens
print(df_dados_oscar['Vencedor'].value_counts)
# dataframe utilizado [coluna].value_counts

<bound method IndexOpsMixin.value_counts of 0         Yes
1           Y
2          No
3        True
4           1
5           1
6           1
7     Winner!
8         Yes
9         Sim
10        Yes
11       True
12       TRUE
13        Yes
14          N
15          0
16        NaN
17        Yes
18        Yes
Name: Vencedor, dtype: object>

In [ ]:
#remover tudo que é duplicado
#guardo no sistema o valor atual de linhas

linhas_antes = len(df_dados_oscar)
#remover duplicatas
#para remover, você chama a base de dados fala que ela recebe ela mesma com o
#atributo drop_duplicate()

df_dados_oscar = df_dados_oscar.drop_duplicates()

In [ ]:
display(df_dados_oscar.head(20))

,Ano,Categoria,Indicado,Vencedor,Nota
0,2024,Best Picture,Oppenheimer,Yes,Filme biográfico
1,2024,Best Pictue,Oppenheimmer,Y,Erro de digitação no nome e categoria
2,24,Best Picture,Barbie,No,Ano incompleto
3,2023,best picture,Everything Everywhere All at Once,True,Case inconsistente
4,2023,BEST PICTURE,Everything Everywhere All at Once,1,Duplicado com formato diferente
5,2020,Best Picture,Parasite,1,Espaços extras
6,2020,Best Picture,Parasite,1,Linha duplicada
7,1895,Melhor Filme,L'Arrivée d'un train en gare de La Ciotat,Winner!,Data impossível (Óscares não existiam)
8,NaN,Best Actor,Cillian Murphy,Yes,Ano ausente
9,2022,Best Picture,CODA,Sim,Idioma do boleano alterado
10,1994/03/21,Best Picture,Schindler's List,Yes,Formato de data completo (AAAA/MM/DD)
11,2021,Actor in a Supporting Role,Daniel Kaluuya,True,NaN
12,2021,ACTOR IN A SUPPORTING ROLE,Daniel Kaluuya,TRUE,Outra variação de case
13,dois mil e dez,Best Picture,The King's Speech,Yes,Ano por extenso
14,2019,Best Picture,Green Book,N,NaN
15,2019,Best Picture,Green Book,0,Representação diferente para 'Não'
16,2024,Best Director,Christopher Nolan,NaN,Vencedor em falta
17,2024,Best Director,Christopher Nolan,Yes,Espaço no início do nome
18,2050,Best Picture,Future Movie,Yes,Data no futuro

In [ ]:
#mostrar valores unicos
print(df_dados_oscar['Vencedor'].unique())

['Yes' 'Y' 'No' 'True' '1' 'Winner!' 'Sim' 'TRUE' 'N' '0' nan]

In [ ]:
#Vamos converter todos os dados para True ou False apenas
mapa_vencedores = {
    'Yes':True, 'Y': True, 'Sim': True, 'Winner!':True, '1':True,'True':True,
    'No':False, 'N':False,'0':False,'nan':False
}

#trocando os dados
# chamamos a base de dados com a coluna, fazemos ela receber ela mesmo com a
# coluna e usamos o atributo map para mapear os novos dados

df_dados_oscar['Vencedor'] = df_dados_oscar['Vencedor'].map(mapa_vencedores)
#para eliminar um dado nulo, vazio ou NaN
#chamamos a base de dados com a coluna, fazemos ela receber ela mesma com a coluna
# e usamos o atributo fillna('Valor desejado')
df_dados_oscar['Vencedor'] = df_dados_oscar['Vencedor'].fillna(False)

display(df_dados_oscar.head(20))

/tmp/ipykernel_13946/1295472694.py:15: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_dados_oscar['Vencedor'] = df_dados_oscar['Vencedor'].fillna(False)

,Ano,Categoria,Indicado,Vencedor,Nota
0,2024,Best Picture,Oppenheimer,True,Filme biográfico
1,2024,Best Pictue,Oppenheimmer,True,Erro de digitação no nome e categoria
2,24,Best Picture,Barbie,False,Ano incompleto
3,2023,best picture,Everything Everywhere All at Once,True,Case inconsistente
4,2023,BEST PICTURE,Everything Everywhere All at Once,True,Duplicado com formato diferente
5,2020,Best Picture,Parasite,True,Espaços extras
6,2020,Best Picture,Parasite,True,Linha duplicada
7,1895,Melhor Filme,L'Arrivée d'un train en gare de La Ciotat,True,Data impossível (Óscares não existiam)
8,NaN,Best Actor,Cillian Murphy,True,Ano ausente
9,2022,Best Picture,CODA,True,Idioma do boleano alterado
10,1994/03/21,Best Picture,Schindler's List,True,Formato de data completo (AAAA/MM/DD)
11,2021,Actor in a Supporting Role,Daniel Kaluuya,True,NaN
12,2021,ACTOR IN A SUPPORTING ROLE,Daniel Kaluuya,False,Outra variação de case
13,dois mil e dez,Best Picture,The King's Speech,True,Ano por extenso
14,2019,Best Picture,Green Book,False,NaN
15,2019,Best Picture,Green Book,False,Representação diferente para 'Não'
16,2024,Best Director,Christopher Nolan,False,Vencedor em falta
17,2024,Best Director,Christopher Nolan,True,Espaço no início do nome
18,2050,Best Picture,Future Movie,True,Data no futuro

In [ ]:
#corrigir dados escritos errados
#chamamos a base de dados, com a coluna, fazemos ela receber ela mesma com a coluna e usamos
# o método replace('antes, depois')
df_dados_oscar['Indicado']=df_dados_oscar['Indicado'].replace({'Oppenheimmer':'Oppenheimer'})
display(df_dados_oscar.head(2))

,Ano,Categoria,Indicado,Vencedor,Nota
0,2024,Best Picture,Oppenheimer,True,Filme biográfico
1,2024,Best Pictue,Oppenheimer,True,Erro de digitação no nome e categoria